import Head from 'next/head';
import Catalog from '../components/Catalog';

export default function ItemsCatalog({}) {
  return (
    <>
      <Head>
        <title>BikeShop: Каталог</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fav_logo.ico" />
      </Head>
      <main>
        <section className="mainContainer">
          <Catalog />
        </section>
      </main>
    </>
  );
}
